#!/usr/bin/env python3
"""Generate the Codex-side agent system from the tracked Claude-side definitions.

    python tools/kb/sync_codex.py            # install / update
    python tools/kb/sync_codex.py --check    # report drift, change nothing (exit 1 if stale)
    python tools/kb/sync_codex.py --dry-run  # show what would be written
    python tools/kb/sync_codex.py --append-default-rules

Source of truth is `.claude/agents/*.md` and `.claude/commands/*.md`, which are tracked in
git and therefore travel with every clone. Codex reads skills and prompts from `$CODEX_HOME`
(default `~/.codex`), which is *outside* the repo and user-level, so those artifacts cannot
travel and must be regenerated per machine — exactly like `.git/hooks`.

Two adaptations are applied rather than copying text verbatim, because Codex does not run
the repository's Claude Code lifecycle hooks and Codex collaboration capabilities vary by
runtime:

  * no hooks  -> nothing injects staleness at session start or routes an edit, so each
                 generated skill carries an explicit "do this yourself" preamble;
  * dispatch-aware routing -> when collaboration tools are available, bounded work is
                 routed to the appropriate role with non-overlapping write scope; limited
                 builds fall back to sequential role adoption. S6 uses a fresh-context
                 referee worker, or a separate session when dispatch is unavailable.

Skills in Codex are global, so every skill is prefixed `godmax-` and its description is
scoped to this repository to avoid polluting unrelated projects.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from kb import parse_frontmatter  # noqa: E402  (same directory, single source of truth)

REPO = Path(__file__).resolve().parents[2]
SRC_AGENTS = REPO / ".claude" / "agents"
SRC_COMMANDS = REPO / ".claude" / "commands"
RULES_SRC = REPO / "tools" / "kb" / "codex" / "godmax.rules"

CODEX_HOME = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))
SKILLS_DIR = CODEX_HOME / "skills"
PROMPTS_DIR = CODEX_HOME / "prompts"
RULES_DIR = CODEX_HOME / "rules"
MANIFEST = SKILLS_DIR / ".godmax-manifest.json"

PREFIX = "godmax-"
# Bump when build_skill/build_prompt/rewrite_agent_refs change semantics, so
# `--check` reports installed artifacts as stale and they get regenerated.
REWRITE_VERSION = "3"
RULES_BEGIN = "# >>> GODMAX kb rules (generated by tools/kb/sync_codex.py) >>>"
RULES_END = "# <<< GODMAX kb rules <<<"

OK, WARN, BAD, DIM, END = "\033[32m", "\033[33m", "\033[31m", "\033[2m", "\033[0m"
if not sys.stdout.isatty() or os.environ.get("NO_COLOR"):
    OK = WARN = BAD = DIM = END = ""


def _c(color: str, text: str) -> str:
    return f"{color}{text}{END}"


# --------------------------------------------------------------------------------------
# Adaptation text
# --------------------------------------------------------------------------------------

CODEX_PREAMBLE = """\
## Running under Codex

Codex does not run the repository's Claude Code lifecycle hooks. Supply those checks
yourself:

**No lifecycle hooks fire.** Nothing has told you what is stale, and nothing will remind you at the
end. Do it manually:

```bash
python tools/kb/kb.py status                 # what is verified vs stale
python tools/kb/kb.py which <files>          # owning documents + invariants (routing)
python tools/kb/kb.py invariants --check     # the executable rules
# ... and before you finish:
python tools/kb/kb.py verify --doc <id> --evidence <ledger>
python tools/kb/kb.py journal "<what changed and why>" --agent <this role>
```

**Use bounded role dispatch when collaboration tools are available.** Where the role below
says "route to X" or "delegate to X", launch the corresponding `godmax-*` role with:

- an observable outcome, exact read/write paths, routed documents and invariants;
- a pre-registered prediction and falsifier;
- required evidence, including the null control; and
- explicit prohibited actions.

All workers share the same worktree. Parallelise read-only investigations or disjoint write
scopes only; exactly one agent writes a given file, and the root coordinator integrates the
result. If collaboration tools are unavailable or slots are exhausted, adopt the roles
sequentially.

**Keep S6 independent.** For any change touching physics, conventions, statistics, or a
number that will be quoted, launch a fresh-context `godmax-physics-referee` worker and give
it only the claim, evidence ledger, changed paths and routed invariants — not the author's
reasoning. The referee is read-only and never fixes the change. If dispatch is unavailable,
use a separate Codex task/session. Same-session self-review is allowed only for mechanical
changes and must be labelled non-independent.

**What does still work identically:** every `tools/kb/kb.py` command, and all four git hooks.
The `pre-push` gate blocks under Codex exactly as under Claude Code, so knowledge freshness,
blocker invariants, the journal requirement, and the tolerance sentinel are all still
mechanically enforced at the push boundary.

---
"""

PROMPT_NOTE = """\

---
*Codex notes: this prompt came from `.claude/commands/` via `tools/kb/sync_codex.py`. If your
Codex build does not substitute `$1` / `$ARGUMENTS`, supply the argument inline when you
invoke it. No hooks fire under Codex — run the `kb` commands shown above yourself.*
"""


def prefixed(name: str) -> str:
    """Namespace a name into the global Codex skill/prompt namespace.

    Skills and prompts live in $CODEX_HOME and are offered in *every* Codex session, so
    generic names like `validate` would collide across projects. Everything is namespaced,
    without doubling the prefix for an agent already called `godmax-core`.
    """
    return name if name.startswith("godmax") else PREFIX + name


def agent_names() -> list[str]:
    """Agent names, longest first so replacement cannot clip a longer name."""
    return sorted((p.stem for p in SRC_AGENTS.glob("*.md")), key=len, reverse=True)


def rewrite_agent_refs(text: str, names: list[str]) -> str:
    """Rewrite prose references to sibling agents into Codex skill names.

    Only inline-code (`name`) and bold (**name**) forms *outside* fenced code blocks are
    rewritten. Inside a fence the plain agent name must survive verbatim, because
    `kb journal --agent measurement-namaster` and `kb verify --agent ...` are matched
    against the `owner:` field of knowledge documents, which uses the unprefixed name.
    Prefixing there would break the ownership check in kb.py.
    """
    out: list[str] = []
    in_fence = False
    for line in text.split("\n"):
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if not in_fence:
            for a in names:
                if a.startswith("godmax"):
                    continue  # already namespaced
                line = line.replace(f"`{a}`", f"`{prefixed(a)}`")
                line = line.replace(f"**{a}**", f"**{prefixed(a)}**")
            line = re.sub(r"`\.claude/agents/([a-z0-9-]+)\.md`",
                          lambda m: f"skill `{prefixed(m.group(1))}`", line)
        out.append(line)
    return "\n".join(out)


def yaml_q(s: str) -> str:
    """Quote a string for a YAML double-quoted scalar."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def scoped_description(agent: str, desc: str) -> str:
    desc = " ".join(desc.split())
    return (f"GODMAX repository only (halo-model cosmology, ~/Documents/GODMAX). {desc} "
            f"Follow knowledge/70-validation/VALIDATION_LOOP.md; run the kb lifecycle "
            f"commands manually under Codex and use bounded role dispatch when available.")


def build_skill(path: Path) -> tuple[str, str]:
    """Return (skill_name, SKILL.md text) for a Claude agent definition."""
    meta, body = parse_frontmatter(path.read_text(encoding="utf-8"))
    agent = str(meta.get("name") or path.stem)
    name = prefixed(agent)
    desc = scoped_description(agent, str(meta.get("description", "")))

    # `tools:` and `model:` are Claude-specific; Codex has no per-skill equivalent, so they
    # are dropped. Bare `.claude/agents/` directory mentions are left alone: the directory
    # is tracked in git and readable from a Codex session, so the path stays correct.
    body = rewrite_agent_refs(body.strip(), agent_names())

    text = (
        "---\n"
        f"name: {yaml_q(name)}\n"
        f"description: {yaml_q(desc)}\n"
        "---\n\n"
        f"# {agent}\n\n"
        f"{CODEX_PREAMBLE}\n"
        f"{body}\n"
    )
    return name, text


def build_prompt(path: Path) -> tuple[str, str]:
    """Return (prompt_name, prompt text) for a Claude slash command."""
    meta, body = parse_frontmatter(path.read_text(encoding="utf-8"))
    name = prefixed(path.stem)
    desc = " ".join(str(meta.get("description", "")).split())
    # Claude frontmatter keys (description / argument-hint / allowed-tools) are not part of
    # the Codex prompt format. Strip the block and fold the description into prose so no
    # literal YAML is injected into the prompt.
    head = f"**{desc}**\n\n" if desc else ""
    hint = str(meta.get("argument-hint", "")).strip()
    if hint:
        head += f"*Argument:* {hint}\n\n"
    body = rewrite_agent_refs(body.strip(), agent_names())
    return name, head + body + "\n" + PROMPT_NOTE


# --------------------------------------------------------------------------------------
# Manifest / drift
# --------------------------------------------------------------------------------------

def source_digest() -> str:
    h = hashlib.sha256()
    for p in sorted(list(SRC_AGENTS.glob("*.md")) + list(SRC_COMMANDS.glob("*.md"))):
        h.update(str(p.relative_to(REPO)).encode())
        h.update(b"\0")
        h.update(hashlib.sha256(p.read_bytes()).hexdigest().encode())
        h.update(b"\n")
    h.update(CODEX_PREAMBLE.encode())          # regenerate if the adaptation text changes
    h.update(REWRITE_VERSION.encode())         # ...or if the rewrite logic changes
    h.update(PROMPT_NOTE.encode())
    return "sha256:" + h.hexdigest()[:32]


def read_manifest() -> dict:
    if not MANIFEST.exists():
        return {}
    try:
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def cmd_check() -> int:
    want = source_digest()
    man = read_manifest()
    have = man.get("source_digest")
    missing = []
    for p in sorted(SRC_AGENTS.glob("*.md")):
        if not (SKILLS_DIR / prefixed(p.stem) / "SKILL.md").exists():
            missing.append(f"skill {prefixed(p.stem)}")
    for p in sorted(SRC_COMMANDS.glob("*.md")):
        if not (PROMPTS_DIR / f"{prefixed(p.stem)}.md").exists():
            missing.append(f"prompt {prefixed(p.stem)}")

    if not have:
        print(_c(WARN, f"codex artifacts not installed under {CODEX_HOME}"))
        print("  run: python tools/kb/sync_codex.py")
        return 1
    if missing:
        print(_c(WARN, f"{len(missing)} codex artifact(s) missing: "
                       f"{', '.join(missing[:6])}"))
        print("  run: python tools/kb/sync_codex.py")
        return 1
    if have != want:
        print(_c(WARN, "codex artifacts are STALE relative to .claude/ sources"))
        print(f"  installed: {have}\n  sources:   {want}")
        print("  run: python tools/kb/sync_codex.py")
        return 1
    print(_c(OK, f"codex artifacts current ({man.get('n_skills', '?')} skills, "
                 f"{man.get('n_prompts', '?')} prompts) at {CODEX_HOME}"))
    return 0


# --------------------------------------------------------------------------------------
# Rules
# --------------------------------------------------------------------------------------

def install_rules(append_default: bool, dry: bool) -> None:
    if not RULES_SRC.exists():
        print(f"  {_c(WARN,'skip')} {RULES_SRC.relative_to(REPO)} not found")
        return
    block = RULES_SRC.read_text(encoding="utf-8").strip()
    if append_default:
        target = RULES_DIR / "default.rules"
        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        if RULES_BEGIN in existing:
            head = existing.split(RULES_BEGIN)[0].rstrip()
            tail = existing.split(RULES_END)[-1].lstrip() if RULES_END in existing else ""
            existing = (head + "\n\n" + tail).strip()
        new = (existing + "\n\n" + RULES_BEGIN + "\n" + block + "\n" + RULES_END + "\n").lstrip()
        if dry:
            print(f"  would append GODMAX block to {target}")
            return
        RULES_DIR.mkdir(parents=True, exist_ok=True)
        if target.exists():
            shutil.copyfile(target, target.with_suffix(".rules.bak"))
        target.write_text(new, encoding="utf-8")
        print(f"  {_c(OK,'appended')} {target}  (backup: default.rules.bak)")
    else:
        target = RULES_DIR / "godmax.rules"
        if dry:
            print(f"  would write {target}")
            return
        RULES_DIR.mkdir(parents=True, exist_ok=True)
        target.write_text(block + "\n", encoding="utf-8")
        print(f"  {_c(OK,'wrote')} {target}")
        hint = ("if your Codex build reads only default.rules, "
                "re-run with --append-default-rules")
        print(f"       {_c(DIM, hint)}")


# --------------------------------------------------------------------------------------
# Install
# --------------------------------------------------------------------------------------

def cmd_install(dry: bool, append_default: bool) -> int:
    if not SRC_AGENTS.is_dir():
        print(_c(BAD, f"missing {SRC_AGENTS.relative_to(REPO)}"))
        return 2

    print(f"\n{_c(DIM,'sync_codex')}  CODEX_HOME={CODEX_HOME}"
          f"{'  (dry run)' if dry else ''}\n")

    n_skills = 0
    print("skills:")
    for p in sorted(SRC_AGENTS.glob("*.md")):
        name, text = build_skill(p)
        d = SKILLS_DIR / name
        if dry:
            print(f"  would write {d}/SKILL.md  ({len(text)} bytes)")
        else:
            d.mkdir(parents=True, exist_ok=True)
            (d / "SKILL.md").write_text(text, encoding="utf-8")
            print(f"  {_c(OK,'ok')} {name}")
        n_skills += 1

    n_prompts = 0
    print("\nprompts:")
    for p in sorted(SRC_COMMANDS.glob("*.md")):
        name, text = build_prompt(p)
        f = PROMPTS_DIR / f"{name}.md"
        if dry:
            print(f"  would write {f}  ({len(text)} bytes)")
        else:
            PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
            f.write_text(text, encoding="utf-8")
            print(f"  {_c(OK,'ok')} /{name}")
        n_prompts += 1

    print("\nrules:")
    install_rules(append_default, dry)

    # Remove skills from a previous sync whose source agent no longer exists.
    if not dry and SKILLS_DIR.is_dir():
        current = {prefixed(p.stem) for p in SRC_AGENTS.glob("*.md")}
        for d in sorted(SKILLS_DIR.glob(f"{PREFIX}*")):
            if d.is_dir() and d.name not in current:
                shutil.rmtree(d)
                print(f"\n  {_c(WARN,'removed orphan skill')} {d.name}")

    if not dry:
        SKILLS_DIR.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(json.dumps({
            "source_digest": source_digest(),
            "n_skills": n_skills,
            "n_prompts": n_prompts,
            "repo": str(REPO),
            "generated_by": "tools/kb/sync_codex.py",
        }, indent=2), encoding="utf-8")

    print(f"\n{_c(OK,'done')} {n_skills} skills, {n_prompts} prompts\n")
    print("In Codex: the skills are offered by description; prompts are /<name>.")
    print("Verify: python tools/kb/sync_codex.py --check\n")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(prog="sync_codex")
    ap.add_argument("--check", action="store_true",
                    help="report drift only; exit 1 if stale or missing")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--append-default-rules", action="store_true",
                    help="merge the kb rules into default.rules instead of godmax.rules")
    a = ap.parse_args()
    if a.check:
        return cmd_check()
    return cmd_install(a.dry_run, a.append_default_rules)


if __name__ == "__main__":
    sys.exit(main())
