"""Create an executable pasted-map active-NPE comparison notebook.

The first version of this generator produced a mostly static report with only
pre-rendered figures.  This version writes a notebook that reloads all saved
products and recomputes the comparison tables and plots in-place.
"""

from __future__ import annotations

import argparse
import json
import pathlib


THIS_DIR = pathlib.Path(__file__).resolve().parent
DEFAULT_INPUT_DIR = THIS_DIR / "outputs" / "map_npe_pasted_256"
DEFAULT_OUTPUT = THIS_DIR / "05_compare_map_npe_to_hmc.ipynb"


def md_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in source.split("\n")],
    }


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in source.split("\n")],
    }


def build_cells(input_dir: pathlib.Path) -> list[dict]:
    input_dir = input_dir.resolve()
    return [
        md_cell(
            "# Pasted-Map Active NPE vs Analytical HMC\n\n"
            "This notebook reloads the saved pasted-map active-NPE validation run "
            "and compares it against the strict analytical HMC benchmark and the "
            "analytical score-compressed Student-t likelihood.  The validation "
            "truth is used only for plotting diagnostics."
        ),
        code_cell(
            "from pathlib import Path\n"
            "import json\n"
            "import warnings\n\n"
            "import matplotlib.pyplot as plt\n"
            "import numpy as np\n"
            "%matplotlib inline\n\n"
            "warnings.filterwarnings('ignore', category=UserWarning)\n"
            "plt.rcParams.update({'figure.dpi': 130})\n\n"
            "CANDIDATE_DIRS = [\n"
            "    Path.cwd(),\n"
            "    Path.cwd() / 'notebooks' / 'SBI_validate',\n"
            "    Path('/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/SBI_validate'),\n"
            "]\n"
            "THIS_DIR = next(p for p in CANDIDATE_DIRS if (p / 'outputs').exists())\n"
            f"INPUT_DIR = Path(r'{input_dir}')\n"
            "if not INPUT_DIR.exists():\n"
            "    INPUT_DIR = THIS_DIR / 'outputs' / 'map_npe_pasted_256'\n\n"
            "THEORY_DIR = THIS_DIR / 'outputs' / 'theory_sbi'\n"
            "HMC_DIR = THEORY_DIR / 'joint_gg_gy_gtau_gkappa_linearized_hmc_strict'\n"
            "ANALYTIC_DIR = THEORY_DIR / 'compressed_likelihood_student_t_nsim256'\n"
            "FIDUCIAL_PRODUCT = THEORY_DIR / 'fiducial_thetaej2_nuejm_minus0p1.npz'\n\n"
            "PARAM_NAMES = ['theta_ej_0', 'nu_theta_ej_M']\n"
            "PARAM_LABELS = [r'\\theta_{\\rm ej,0}', r'\\nu^M_{\\theta_{\\rm ej}}']\n\n"
            "print('notebook dir:', THIS_DIR)\n"
            "print('map NPE dir:', INPUT_DIR)\n"
            "print('HMC dir:', HMC_DIR)\n"
            "print('analytical compressed dir:', ANALYTIC_DIR)"
        ),
        code_cell(
            "def load_json(path):\n"
            "    path = Path(path)\n"
            "    return json.loads(path.read_text()) if path.exists() else {}\n\n"
            "def require(path):\n"
            "    path = Path(path)\n"
            "    if not path.exists():\n"
            "        raise FileNotFoundError(path)\n"
            "    return path\n\n"
            "def load_hmc_samples(npz):\n"
            "    return np.column_stack([npz[f'samples_{name}'] for name in PARAM_NAMES])\n\n"
            "def load_hmc_chains(npz):\n"
            "    return {name: np.asarray(npz[f'samples_chain_{name}']) for name in PARAM_NAMES}\n\n"
            "def prior_filter(samples, prior_min, prior_max):\n"
            "    samples = np.asarray(samples, dtype=float)\n"
            "    finite = np.all(np.isfinite(samples), axis=1)\n"
            "    inside = np.all((samples >= prior_min[None, :]) & (samples <= prior_max[None, :]), axis=1)\n"
            "    return samples[finite & inside], finite & inside\n\n"
            "def hmc_directions(hmc_samples, fiducial):\n"
            "    cov = np.cov(hmc_samples.T)\n"
            "    evals, evecs = np.linalg.eigh(cov)\n"
            "    constrained = evecs[:, 0].copy()\n"
            "    degenerate = evecs[:, 1].copy()\n"
            "    if constrained[1] > 0:\n"
            "        constrained *= -1.0\n"
            "    if degenerate[0] < 0:\n"
            "        degenerate *= -1.0\n"
            "    return evals, constrained, degenerate\n\n"
            "def project_direction(samples, fiducial, vec):\n"
            "    return (np.asarray(samples) - fiducial[None, :]) @ vec\n\n"
            "def summarize_samples(label, samples, hmc_ref, fiducial, constrained_vec, degenerate_vec, nsim, likelihood):\n"
            "    samples = np.asarray(samples, dtype=float)\n"
            "    q_ref = project_direction(hmc_ref, fiducial, constrained_vec)\n"
            "    d_ref = project_direction(hmc_ref, fiducial, degenerate_vec)\n"
            "    q = project_direction(samples, fiducial, constrained_vec)\n"
            "    d = project_direction(samples, fiducial, degenerate_vec)\n"
            "    return {\n"
            "        'method': label,\n"
            "        'simulations': nsim,\n"
            "        'likelihood': likelihood,\n"
            "        'theta mean': samples[:, 0].mean(),\n"
            "        'nu mean': samples[:, 1].mean(),\n"
            "        'theta std': samples[:, 0].std(),\n"
            "        'nu std': samples[:, 1].std(),\n"
            "        'theta shift / HMC sigma': (samples[:, 0].mean() - hmc_ref[:, 0].mean()) / hmc_ref[:, 0].std(),\n"
            "        'nu shift / HMC sigma': (samples[:, 1].mean() - hmc_ref[:, 1].mean()) / hmc_ref[:, 1].std(),\n"
            "        'theta width / HMC': samples[:, 0].std() / hmc_ref[:, 0].std(),\n"
            "        'nu width / HMC': samples[:, 1].std() / hmc_ref[:, 1].std(),\n"
            "        'q width / HMC': q.std() / q_ref.std(),\n"
            "        'd width / HMC': d.std() / d_ref.std(),\n"
            "    }\n\n"
            "def show_table(rows, precision=4):\n"
            "    try:\n"
            "        import pandas as pd\n"
            "        display(pd.DataFrame(rows).round(precision))\n"
            "    except Exception:\n"
            "        for row in rows:\n"
            "            print(row)"
        ),
        code_cell(
            "paths = {\n"
            "    'HMC samples': HMC_DIR / 'hmc_samples.npz',\n"
            "    'HMC diagnostics': HMC_DIR / 'hmc_diagnostics.json',\n"
            "    'Analytical compressed samples': ANALYTIC_DIR / 'compressed_likelihood_samples.npz',\n"
            "    'Analytical compressed diagnostics': ANALYTIC_DIR / 'compressed_likelihood_diagnostics.json',\n"
            "    'Map NPE samples': INPUT_DIR / 'map_npe_posterior_samples.npz',\n"
            "    'Map NPE diagnostics': INPUT_DIR / 'map_npe_diagnostics.json',\n"
            "    'Map NPE simulations': INPUT_DIR / 'map_npe_simulations.npz',\n"
            "    'Map NPE observation': INPUT_DIR / 'observation.npz',\n"
            "    'Multi-anchor compressor': INPUT_DIR / 'multi_anchor_compressor.npz',\n"
            "    'Fiducial theory product': FIDUCIAL_PRODUCT,\n"
            "}\n"
            "for label, path in paths.items():\n"
            "    print(f'{label:34s}: {path.exists()}  {path}')\n\n"
            "hmc_npz = np.load(require(paths['HMC samples']), allow_pickle=True)\n"
            "hmc_diag = load_json(paths['HMC diagnostics'])\n"
            "analytic_npz = np.load(require(paths['Analytical compressed samples']), allow_pickle=True)\n"
            "analytic_diag = load_json(paths['Analytical compressed diagnostics'])\n"
            "map_npz = np.load(require(paths['Map NPE samples']), allow_pickle=True)\n"
            "map_diag = load_json(paths['Map NPE diagnostics'])\n"
            "sims_npz = np.load(require(paths['Map NPE simulations']), allow_pickle=True)\n"
            "obs_npz = np.load(require(paths['Map NPE observation']), allow_pickle=True)\n"
            "compressor_npz = np.load(require(paths['Multi-anchor compressor']), allow_pickle=True)\n"
            "fid_npz = np.load(require(paths['Fiducial theory product']), allow_pickle=True)\n\n"
            "hmc_samples = load_hmc_samples(hmc_npz)\n"
            "analytic_samples = np.asarray(analytic_npz['samples'], dtype=float)\n"
            "analytic_exact = np.asarray(analytic_npz['samples_exact'], dtype=float) if 'samples_exact' in analytic_npz.files else None\n"
            "map_samples_raw = np.asarray(map_npz['samples'], dtype=float)\n\n"
            "prior_min = np.asarray(map_npz['prior_min'] if 'prior_min' in map_npz.files else hmc_npz['prior_min'], dtype=float)\n"
            "prior_max = np.asarray(map_npz['prior_max'] if 'prior_max' in map_npz.files else hmc_npz['prior_max'], dtype=float)\n"
            "fiducial = np.asarray(map_npz['theta_validation_truth'] if 'theta_validation_truth' in map_npz.files else hmc_npz['theta_fiducial'], dtype=float)\n\n"
            "map_samples, map_prior_mask = prior_filter(map_samples_raw, prior_min, prior_max)\n"
            "print(f'map NPE samples inside prior: {len(map_samples)} / {len(map_samples_raw)}')\n"
            "print('fiducial validation point:', fiducial)\n"
            "print('prior bounds:', list(zip(prior_min, prior_max)))"
        ),
        md_cell("## Run Metadata"),
        code_cell(
            "run_rows = [\n"
            "    {\n"
            "        'run': 'Strict analytical HMC',\n"
            "        'simulations': 0,\n"
            "        'probes': ','.join(map_diag.get('probes', ['gg', 'gy', 'gtau', 'gkappa'])),\n"
            "        'runtime sec': hmc_diag.get('runtime_sec'),\n"
            "        'notes': f\"Rhat={hmc_diag.get('max_rhat')}, ESS={hmc_diag.get('min_ess_bulk')}\",\n"
            "    },\n"
            "    {\n"
            "        'run': 'Analytical compressed Student-t',\n"
            "        'simulations': analytic_diag.get('nsim', 256),\n"
            "        'probes': ','.join(analytic_diag.get('probes', map_diag.get('probes', []))),\n"
            "        'runtime sec': analytic_diag.get('runtime_sec'),\n"
            "        'notes': analytic_diag.get('likelihood', 'student_t'),\n"
            "    },\n"
            "    {\n"
            "        'run': 'Pasted-map active NPE',\n"
            "        'simulations': map_diag.get('n_valid_simulations', map_diag.get('nsim_total')),\n"
            "        'probes': ','.join(map_diag.get('probes', [])),\n"
            "        'runtime sec': map_diag.get('runtime_sec'),\n"
            "        'notes': f\"rounds={map_diag.get('rounds')}, estimator={map_diag.get('density_estimator')}\",\n"
            "    },\n"
            "]\n"
            "show_table(run_rows, precision=3)\n"
            "print('observation metadata:')\n"
            "print(json.dumps(map_diag.get('observation_metadata', {}), indent=2)[:5000])"
        ),
        md_cell("## Posterior Moment Comparison"),
        code_cell(
            "evals, constrained_vec, degenerate_vec = hmc_directions(hmc_samples, fiducial)\n"
            "print('HMC covariance eigenvalues:', evals)\n"
            "print('most constrained q vector:', constrained_vec)\n"
            "print('broad/degenerate d vector:', degenerate_vec)\n"
            "print('q definition: q = dot(theta - theta_validation, q_vector)')\n\n"
            "summary_rows = [\n"
            "    summarize_samples('Strict HMC', hmc_samples, hmc_samples, fiducial, constrained_vec, degenerate_vec, 0, 'Gaussian likelihood'),\n"
            "    summarize_samples('Analytical compressed Student-t', analytic_samples, hmc_samples, fiducial, constrained_vec, degenerate_vec, analytic_diag.get('nsim', 256), 'Student-t'),\n"
            "    summarize_samples('Pasted-map active NPE', map_samples, hmc_samples, fiducial, constrained_vec, degenerate_vec, map_diag.get('n_valid_simulations', map_diag.get('nsim_total')), 'SNPE-C / MDN'),\n"
            "]\n"
            "if analytic_exact is not None:\n"
            "    summary_rows.insert(1, summarize_samples('Analytical exact score reference', analytic_exact, hmc_samples, fiducial, constrained_vec, degenerate_vec, 0, 'linearized exact'))\n"
            "show_table(summary_rows, precision=4)"
        ),
        md_cell("## GetDist Posterior Overlay"),
        code_cell(
            "try:\n"
            "    from getdist import MCSamples, plots\n"
            "    gd_settings = {'ignore_rows': 0.0, 'smooth_scale_1D': 0.35, 'smooth_scale_2D': 0.35}\n"
            "    samples_for_plot = [\n"
            "        ('Strict HMC', hmc_samples, '#1f77b4', False),\n"
            "        ('Analytical compressed Student-t', analytic_samples, 'black', False),\n"
            "        ('Pasted-map active NPE', map_samples, '#d62728', True),\n"
            "    ]\n"
            "    if analytic_exact is not None:\n"
            "        samples_for_plot.insert(1, ('Analytical exact score', analytic_exact, '#7f7f7f', False))\n"
            "    gd = [\n"
            "        MCSamples(samples=s, names=PARAM_NAMES, labels=PARAM_LABELS, label=label, settings=gd_settings)\n"
            "        for label, s, _, _ in samples_for_plot\n"
            "    ]\n"
            "    g = plots.get_subplot_plotter(width_inch=7.2)\n"
            "    g.settings.figure_legend_frame = False\n"
            "    g.settings.alpha_filled_add = 0.18\n"
            "    g.triangle_plot(\n"
            "        gd,\n"
            "        params=PARAM_NAMES,\n"
            "        filled=[filled for _, _, _, filled in samples_for_plot],\n"
            "        contour_colors=[color for _, _, color, _ in samples_for_plot],\n"
            "        markers={name: value for name, value in zip(PARAM_NAMES, fiducial)},\n"
            "        marker_args={'color': 'black', 'lw': 1.1, 'ls': '--'},\n"
            "    )\n"
            "except Exception as exc:\n"
            "    print('GetDist plot failed; using fallback scatter/hist:', exc)\n"
            "    fig, axes = plt.subplots(2, 2, figsize=(7.5, 7.0), constrained_layout=True)\n"
            "    plot_data = [('HMC', hmc_samples, '#1f77b4'), ('Analytical', analytic_samples, 'black'), ('Map NPE', map_samples, '#d62728')]\n"
            "    for label, samples, color in plot_data:\n"
            "        axes[0, 0].hist(samples[:, 0], bins=70, density=True, histtype='step', color=color, label=label)\n"
            "        axes[1, 1].hist(samples[:, 1], bins=70, density=True, histtype='step', color=color)\n"
            "        keep = np.linspace(0, len(samples) - 1, min(4000, len(samples))).astype(int)\n"
            "        axes[1, 0].scatter(samples[keep, 0], samples[keep, 1], s=3, alpha=0.15, color=color)\n"
            "    axes[0, 0].axvline(fiducial[0], color='black', ls='--')\n"
            "    axes[1, 1].axvline(fiducial[1], color='black', ls='--')\n"
            "    axes[1, 0].scatter([fiducial[0]], [fiducial[1]], marker='*', s=100, color='black')\n"
            "    axes[0, 0].set_xlabel(PARAM_NAMES[0])\n"
            "    axes[1, 1].set_xlabel(PARAM_NAMES[1])\n"
            "    axes[1, 0].set_xlabel(PARAM_NAMES[0])\n"
            "    axes[1, 0].set_ylabel(PARAM_NAMES[1])\n"
            "    axes[0, 1].axis('off')\n"
            "    axes[0, 0].legend(fontsize=8)\n"
            "    plt.show()"
        ),
        md_cell("## Most Constrained Direction"),
        code_cell(
            "fig, axes = plt.subplots(1, 2, figsize=(11.5, 4.0), constrained_layout=True)\n"
            "q_hmc = project_direction(hmc_samples, fiducial, constrained_vec)\n"
            "q_analytic = project_direction(analytic_samples, fiducial, constrained_vec)\n"
            "q_map = project_direction(map_samples, fiducial, constrained_vec)\n"
            "lo = min(np.percentile(q_hmc, 0.2), np.percentile(q_analytic, 0.2), np.percentile(q_map, 0.2))\n"
            "hi = max(np.percentile(q_hmc, 99.8), np.percentile(q_analytic, 99.8), np.percentile(q_map, 99.8))\n"
            "bins = np.linspace(lo, hi, 90)\n"
            "for label, q, color in [\n"
            "    ('Strict HMC', q_hmc, '#1f77b4'),\n"
            "    ('Analytical compressed Student-t', q_analytic, 'black'),\n"
            "    ('Pasted-map active NPE', q_map, '#d62728'),\n"
            "]:\n"
            "    axes[0].hist(q, bins=bins, density=True, histtype='step', lw=1.8, color=color, label=label)\n"
            "axes[0].axvline(0.0, color='black', ls='--', lw=0.9)\n"
            "axes[0].set_xlabel(r'$q = (\\theta-\\theta_{\\rm val})\\cdot e_{\\rm constrained}$')\n"
            "axes[0].set_ylabel('density')\n"
            "axes[0].set_title('Posterior along HMC narrow direction')\n"
            "axes[0].legend(fontsize=8)\n\n"
            "rng = np.random.default_rng(11)\n"
            "for label, samples, color, alpha in [\n"
            "    ('Strict HMC', hmc_samples, '#1f77b4', 0.18),\n"
            "    ('Pasted-map active NPE', map_samples, '#d62728', 0.12),\n"
            "]:\n"
            "    q = project_direction(samples, fiducial, constrained_vec)\n"
            "    keep = rng.choice(len(samples), size=min(5000, len(samples)), replace=False)\n"
            "    axes[1].scatter(samples[keep, 0], q[keep], s=4, alpha=alpha, color=color, label=label, rasterized=True)\n"
            "axes[1].axhline(0.0, color='black', ls='--', lw=0.9)\n"
            "axes[1].axvline(fiducial[0], color='black', ls='--', lw=0.9)\n"
            "axes[1].set_xlabel(PARAM_NAMES[0])\n"
            "axes[1].set_ylabel('q')\n"
            "axes[1].set_title('Narrow direction in physical coordinates')\n"
            "axes[1].legend(fontsize=8)\n"
            "plt.show()"
        ),
        md_cell("## HMC Convergence Diagnostics"),
        code_cell(
            "chains = load_hmc_chains(hmc_npz)\n"
            "diag_rows = []\n"
            "summary = hmc_diag.get('arviz_summary', {})\n"
            "for name in PARAM_NAMES:\n"
            "    diag_rows.append({\n"
            "        'parameter': name,\n"
            "        'Rhat': summary.get('r_hat', {}).get(name),\n"
            "        'ESS bulk': summary.get('ess_bulk', {}).get(name),\n"
            "        'ESS tail': summary.get('ess_tail', {}).get(name),\n"
            "        'mean': summary.get('mean', {}).get(name),\n"
            "        'sd': summary.get('sd', {}).get(name),\n"
            "    })\n"
            "show_table(diag_rows, precision=4)\n\n"
            "fig, axes = plt.subplots(len(PARAM_NAMES), 2, figsize=(11.0, 3.0 * len(PARAM_NAMES)), squeeze=False, constrained_layout=True)\n"
            "for ip, name in enumerate(PARAM_NAMES):\n"
            "    arr = chains[name]\n"
            "    draws = np.arange(1, arr.shape[1] + 1)\n"
            "    for ichain, chain in enumerate(arr):\n"
            "        axes[ip, 0].plot(chain, lw=0.45, alpha=0.75, label=f'chain {ichain}' if ip == 0 else None)\n"
            "    axes[ip, 0].axhline(fiducial[ip], color='black', ls='--', lw=0.9)\n"
            "    axes[ip, 0].set_title(f'HMC trace: {name}')\n"
            "    axes[ip, 0].set_xlabel('post-warmup draw')\n"
            "    axes[ip, 0].set_ylabel(name)\n"
            "    running = np.cumsum(arr, axis=1) / draws[None, :]\n"
            "    for run in running:\n"
            "        axes[ip, 1].plot(draws, run, lw=0.8, alpha=0.8)\n"
            "    axes[ip, 1].axhline(hmc_samples[:, ip].mean(), color='#1f77b4', lw=1.2, label='all-chain mean')\n"
            "    axes[ip, 1].axhline(fiducial[ip], color='black', ls='--', lw=0.9, label='validation truth')\n"
            "    axes[ip, 1].set_title(f'HMC running mean: {name}')\n"
            "    axes[ip, 1].set_xlabel('post-warmup draw')\n"
            "axes[0, 0].legend(fontsize=8)\n"
            "axes[0, 1].legend(fontsize=8)\n"
            "plt.show()\n\n"
            "fig, axes = plt.subplots(1, 3, figsize=(12.0, 3.2), constrained_layout=True)\n"
            "if 'extra_accept_prob' in hmc_npz.files:\n"
            "    axes[0].plot(np.asarray(hmc_npz['extra_accept_prob']).reshape(-1), lw=0.45)\n"
            "    axes[0].set_title('accept probability')\n"
            "if 'extra_num_steps' in hmc_npz.files:\n"
            "    axes[1].plot(np.asarray(hmc_npz['extra_num_steps']).reshape(-1), lw=0.45)\n"
            "    axes[1].set_title('leapfrog steps')\n"
            "if 'extra_diverging' in hmc_npz.files:\n"
            "    div = np.asarray(hmc_npz['extra_diverging']).reshape(-1).astype(int)\n"
            "    axes[2].plot(np.cumsum(div), lw=0.8)\n"
            "    axes[2].set_title(f'cumulative divergences: {div.sum()}')\n"
            "for ax in axes:\n"
            "    ax.set_xlabel('draw')\n"
            "plt.show()"
        ),
        md_cell("## Active-Learning Proposal Diagnostics"),
        code_cell(
            "theta_round_paths = sorted(INPUT_DIR.glob('theta_round*.npz'))\n"
            "round_rows = []\n"
            "theta_by_round = []\n"
            "for path in theta_round_paths:\n"
            "    z = np.load(path, allow_pickle=True)\n"
            "    theta = np.asarray(z['theta'], dtype=float)\n"
            "    iround = int(np.asarray(z['round_index']).reshape(-1)[0])\n"
            "    theta_by_round.append((iround, theta))\n"
            "    round_rows.append({\n"
            "        'round': iround,\n"
            "        'n simulations': len(theta),\n"
            "        'theta mean': theta[:, 0].mean(),\n"
            "        'theta std': theta[:, 0].std(),\n"
            "        'nu mean': theta[:, 1].mean(),\n"
            "        'nu std': theta[:, 1].std(),\n"
            "    })\n"
            "show_table(round_rows, precision=4)\n\n"
            "fig, axes = plt.subplots(1, 2, figsize=(10.8, 3.8), constrained_layout=True)\n"
            "colors = plt.cm.viridis(np.linspace(0.1, 0.9, max(len(theta_by_round), 1)))\n"
            "for color, (iround, theta) in zip(colors, theta_by_round):\n"
            "    axes[0].hist(theta[:, 0], bins=35, density=True, histtype='step', color=color, lw=1.4, label=f'round {iround}')\n"
            "    axes[1].hist(theta[:, 1], bins=35, density=True, histtype='step', color=color, lw=1.4, label=f'round {iround}')\n"
            "for ip, ax in enumerate(axes):\n"
            "    ax.axvline(fiducial[ip], color='black', ls='--', lw=1.0, label='validation truth' if ip == 0 else None)\n"
            "    ax.axvline(hmc_samples[:, ip].mean(), color='#1f77b4', lw=1.0, label='HMC mean' if ip == 0 else None)\n"
            "    ax.set_xlabel(PARAM_NAMES[ip])\n"
            "    ax.set_ylabel('proposal density')\n"
            "axes[0].legend(fontsize=8)\n"
            "plt.show()\n\n"
            "fig, ax = plt.subplots(figsize=(5.5, 4.6), constrained_layout=True)\n"
            "for color, (iround, theta) in zip(colors, theta_by_round):\n"
            "    ax.scatter(theta[:, 0], theta[:, 1], s=16, alpha=0.45, color=color, label=f'round {iround}')\n"
            "ax.scatter([fiducial[0]], [fiducial[1]], marker='*', s=120, color='black', label='validation truth')\n"
            "ax.scatter([hmc_samples[:, 0].mean()], [hmc_samples[:, 1].mean()], marker='x', s=70, color='#1f77b4', label='HMC mean')\n"
            "ax.set_xlabel(PARAM_NAMES[0])\n"
            "ax.set_ylabel(PARAM_NAMES[1])\n"
            "ax.set_title('Parameter proposals used for pasted-map simulations')\n"
            "ax.legend(fontsize=8)\n"
            "plt.show()"
        ),
        md_cell("## NPE Posterior Sample Stability"),
        code_cell(
            "n_map = len(map_samples)\n"
            "n_grid = np.unique(np.geomspace(max(50, min(200, n_map)), n_map, 70).astype(int))\n"
            "hmc_mean = hmc_samples.mean(axis=0)\n"
            "hmc_std = hmc_samples.std(axis=0)\n"
            "fig, axes = plt.subplots(len(PARAM_NAMES), 2, figsize=(11.0, 3.0 * len(PARAM_NAMES)), squeeze=False, constrained_layout=True)\n"
            "for ip, name in enumerate(PARAM_NAMES):\n"
            "    running_mean = np.array([map_samples[:n, ip].mean() for n in n_grid])\n"
            "    running_std = np.array([map_samples[:n, ip].std() for n in n_grid])\n"
            "    axes[ip, 0].plot(n_grid, running_mean, color='#d62728', lw=1.5)\n"
            "    axes[ip, 0].axhline(hmc_mean[ip], color='#1f77b4', lw=1.1, label='HMC mean')\n"
            "    axes[ip, 0].axhspan(hmc_mean[ip] - 0.1 * hmc_std[ip], hmc_mean[ip] + 0.1 * hmc_std[ip], color='#1f77b4', alpha=0.12)\n"
            "    axes[ip, 0].axhline(fiducial[ip], color='black', ls='--', lw=0.9, label='validation truth')\n"
            "    axes[ip, 0].set_xscale('log')\n"
            "    axes[ip, 0].set_title(f'NPE running mean: {name}')\n"
            "    axes[ip, 0].set_xlabel('posterior samples')\n"
            "    axes[ip, 1].plot(n_grid, running_std, color='#d62728', lw=1.5)\n"
            "    axes[ip, 1].axhline(hmc_std[ip], color='#1f77b4', lw=1.1, label='HMC std')\n"
            "    axes[ip, 1].axhspan(0.9 * hmc_std[ip], 1.1 * hmc_std[ip], color='#1f77b4', alpha=0.12)\n"
            "    axes[ip, 1].set_xscale('log')\n"
            "    axes[ip, 1].set_title(f'NPE running std: {name}')\n"
            "    axes[ip, 1].set_xlabel('posterior samples')\n"
            "axes[0, 0].legend(fontsize=8)\n"
            "axes[0, 1].legend(fontsize=8)\n"
            "plt.show()"
        ),
        md_cell("## Compression Feature Diagnostics"),
        code_cell(
            "features_raw = np.asarray(sims_npz['features_raw'], dtype=float)\n"
            "features_mean = np.asarray(sims_npz['features_mean'], dtype=float)\n"
            "features_std = np.asarray(sims_npz['features_std'], dtype=float)\n"
            "features_std_safe = np.where(features_std > 0, features_std, 1.0)\n"
            "features_z = (features_raw - features_mean[None, :]) / features_std_safe[None, :]\n"
            "x_obs_z = np.asarray(sims_npz['x_obs_std'], dtype=float)\n"
            "anchors = np.asarray(compressor_npz['anchors'], dtype=float)\n"
            "feature_labels = []\n"
            "for ia in range(len(anchors)):\n"
            "    for pname in PARAM_NAMES:\n"
            "        feature_labels.append(f'a{ia} {pname}')\n"
            "feature_labels = feature_labels[:features_z.shape[1]]\n\n"
            "fig, axes = plt.subplots(1, 2, figsize=(12.0, 4.0), constrained_layout=True)\n"
            "axes[0].plot(np.nanmean(features_z, axis=0), marker='o', label='training mean')\n"
            "axes[0].plot(np.nanstd(features_z, axis=0), marker='s', label='training std')\n"
            "axes[0].axhline(0.0, color='black', lw=0.8)\n"
            "axes[0].axhline(1.0, color='black', lw=0.8, ls='--')\n"
            "axes[0].set_title('standardized feature moments')\n"
            "axes[0].set_xlabel('feature index')\n"
            "axes[0].legend(fontsize=8)\n"
            "axes[1].bar(np.arange(len(x_obs_z)), x_obs_z, color='#d62728', alpha=0.75)\n"
            "axes[1].axhline(0.0, color='black', lw=0.8)\n"
            "axes[1].axhline(2.0, color='black', lw=0.8, ls='--')\n"
            "axes[1].axhline(-2.0, color='black', lw=0.8, ls='--')\n"
            "axes[1].set_title('observed compressed features')\n"
            "axes[1].set_xlabel('feature index')\n"
            "axes[1].set_ylabel('standardized value')\n"
            "plt.show()\n\n"
            "corr = np.corrcoef(features_z, rowvar=False)\n"
            "fig, ax = plt.subplots(figsize=(6.0, 5.0), constrained_layout=True)\n"
            "im = ax.imshow(corr, origin='lower', cmap='coolwarm', vmin=-1, vmax=1)\n"
            "ax.set_title('training feature correlation')\n"
            "ax.set_xlabel('feature index')\n"
            "ax.set_ylabel('feature index')\n"
            "fig.colorbar(im, ax=ax, fraction=0.046)\n"
            "plt.show()\n\n"
            "print('anchors used for multi-anchor score compression:')\n"
            "show_table([{'anchor': i, 'theta_ej_0': a[0], 'nu_theta_ej_M': a[1]} for i, a in enumerate(anchors)], precision=4)"
        ),
        md_cell("## Map Cl Ensemble vs Analytical Fiducial Theory"),
        code_cell(
            "probes = list(map_diag.get('probes', ['gg', 'gy', 'gtau', 'gkappa']))\n"
            "ell = np.asarray(sims_npz['ell'], dtype=float)\n"
            "nell = len(ell)\n"
            "fid_ell = np.asarray(fid_npz['ell'], dtype=float)\n"
            "fid_index = np.array([int(np.argmin(np.abs(fid_ell - e))) for e in ell])\n"
            "data_vectors = np.asarray(sims_npz['data_vector'], dtype=float)\n"
            "obs_vector = np.asarray(obs_npz['data_vector'], dtype=float)\n\n"
            "fig, axes = plt.subplots(len(probes), 2, figsize=(11.5, 2.65 * len(probes)), squeeze=False, constrained_layout=True)\n"
            "ratio_rows = []\n"
            "for iprobe, probe in enumerate(probes):\n"
            "    sl = slice(iprobe * nell, (iprobe + 1) * nell)\n"
            "    sim_block = data_vectors[:, sl]\n"
            "    obs_block = obs_vector[sl]\n"
            "    theory = np.asarray(fid_npz[f'cl_{probe}'], dtype=float)[fid_index]\n"
            "    mean = np.nanmean(sim_block, axis=0)\n"
            "    p16, p84 = np.nanpercentile(sim_block, [16, 84], axis=0)\n"
            "    ax = axes[iprobe, 0]\n"
            "    ax.loglog(ell, np.abs(theory), color='black', lw=1.5, label='theory abs')\n"
            "    ax.loglog(ell, np.abs(mean), color='#d62728', lw=1.4, label='simulation mean abs')\n"
            "    ax.fill_between(ell, np.abs(p16), np.abs(p84), color='#d62728', alpha=0.18, linewidth=0, label='16-84%' if iprobe == 0 else None)\n"
            "    ax.scatter(ell, np.abs(obs_block), color='#1f77b4', s=18, label='observed pseudo-data abs')\n"
            "    ax.set_title(probe)\n"
            "    ax.set_xlabel(r'$\\ell$')\n"
            "    ax.set_ylabel(r'$|C_\\ell|$')\n"
            "    ax.legend(fontsize=8)\n"
            "    ax = axes[iprobe, 1]\n"
            "    ratio_mean = mean / theory\n"
            "    ratio_obs = obs_block / theory\n"
            "    ax.axhline(1.0, color='black', lw=1.0)\n"
            "    ax.plot(ell, ratio_mean, color='#d62728', marker='o', ms=3, label='simulation mean / theory')\n"
            "    ax.scatter(ell, ratio_obs, color='#1f77b4', s=18, label='observed / theory')\n"
            "    ax.set_xscale('log')\n"
            "    ax.set_title(f'{probe} ratios')\n"
            "    ax.set_xlabel(r'$\\ell$')\n"
            "    ax.set_ylabel('ratio')\n"
            "    ax.legend(fontsize=8)\n"
            "    sel = np.isfinite(ratio_mean) & np.isfinite(ratio_obs) & (np.abs(theory) > 0)\n"
            "    ratio_rows.append({\n"
            "        'probe': probe,\n"
            "        'median sim/theory': np.nanmedian(ratio_mean[sel]),\n"
            "        'median obs/theory': np.nanmedian(ratio_obs[sel]),\n"
            "        'p16 sim/theory': np.nanpercentile(ratio_mean[sel], 16),\n"
            "        'p84 sim/theory': np.nanpercentile(ratio_mean[sel], 84),\n"
            "    })\n"
            "plt.show()\n"
            "show_table(ratio_rows, precision=4)"
        ),
        md_cell("## Raw Diagnostics"),
        code_cell(
            "print('map NPE diagnostics:')\n"
            "print(json.dumps(map_diag, indent=2)[:8000])\n"
            "print('\\nanalytical compressed diagnostics:')\n"
            "print(json.dumps(analytic_diag, indent=2)[:4000])\n"
            "print('\\nHMC diagnostics:')\n"
            "print(json.dumps(hmc_diag, indent=2)[:4000])"
        ),
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=pathlib.Path, default=DEFAULT_INPUT_DIR)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    nb = {
        "cells": build_cells(args.input_dir),
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "pygments_lexer": "ipython3",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(nb, indent=1))
    print(f"Wrote notebook to {args.output.resolve()}")


if __name__ == "__main__":
    main()
