#!/bin/bash
#SBATCH --account=bdne-dtai-gh
#SBATCH --partition=ghx4
#SBATCH --nodes=1
#SBATCH --time=00:45:00
#SBATCH --gpus=1
#SBATCH --mem=400G
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=anshumana@berkeley.edu
#SBATCH --array=0-119           # 30 samples * 4 splits = 120 tasks (0 to 119)
#SBATCH --output=/work/hdd/bdne/aacharya2/GODMAX/notebooks/CMASSfirstbin/run_scripts/logs/R2_%A_%a.out

# Configuration
NSIDE=512
TOTAL_SPLITS=4
WORK_DIR="/work/hdd/bdne/aacharya2/GODMAX/notebooks/CMASSfirstbin"
# Update this to your Round 2 CSV generated by the bridge code
CSV_FILE="${WORK_DIR}/round2_samples.csv"

# --- 2D Array Logic ---
# SLURM_ARRAY_TASK_ID 0-3 -> Sample Index 0
# SLURM_ARRAY_TASK_ID 4-7 -> Sample Index 1 ...
SAMPLE_IDX=$((SLURM_ARRAY_TASK_ID / TOTAL_SPLITS))
JDEVICE=$((SLURM_ARRAY_TASK_ID % TOTAL_SPLITS))

# Extract parameters for the Sample Index (Row = IDX + 2 to skip header)
LINE_NUM=$((SAMPLE_IDX + 2))
PARAMS=$(sed -n "${LINE_NUM}p" "$CSV_FILE")

# Parse CSV
# Note: round2_samples.csv format: sample_id, theta_ej_0, nu_theta_ej_M, nu_theta_ej_z, mu_beta
INTERNAL_ID=$(echo $PARAMS | cut -d',' -f1)
THETA_0=$(echo $PARAMS | cut -d',' -f2)
NU_M=$(echo $PARAMS | cut -d',' -f3)
NU_Z=$(echo $PARAMS | cut -d',' -f4)
MU_B=$(echo $PARAMS | cut -d',' -f5)

# Offset ID: Round 1 was 0-29. Round 2 should be 30-49.
# We add 30 to the index to create unique folder names
FINAL_ID=$((SAMPLE_IDX + 30))

echo "Task ${SLURM_ARRAY_TASK_ID}: R2 Sample Index ${SAMPLE_IDX} (ID ${FINAL_ID}), Split ${JDEVICE} of ${TOTAL_SPLITS}"

module purge
module load gcc-native/12.3 cuda/12.2.0 cudnn/9.3.0.75
cd "${WORK_DIR}"

# Note: We pass --sample_id ${FINAL_ID} so it creates /sample_30, /sample_31, etc.
conda run -n godmax_env bash -c "export PYTHONNOUSERSITE=1; LD_LIBRARY_PATH= python run_backlight_pkdgrav_all_maps.py \
    --nside ${NSIDE} \
    --jdevice ${JDEVICE} \
    --ndevices ${TOTAL_SPLITS} \
    --theta_ej_0 ${THETA_0} \
    --nu_theta_ej_M ${NU_M} \
    --nu_theta_ej_z ${NU_Z} \
    --mu_beta ${MU_B} \
    --sample_id ${FINAL_ID}"
